version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
  build:
    commands:
      - . ./assume-role.sh ${DEV_PIPELINE_EXECUTION_ROLE} deploy
      - sam deploy --stack-name ${DEV_STACK_NAME}
                    --template ${DEV_TEMPLATE}
                    --capabilities CAPABILITY_IAM
                    --region ${DEV_REGION}
                    --s3-bucket ${DEV_BUCKET}
                    --no-fail-on-empty-changeset
